### ISSUE TITLE
TypeError: descriptor 'strip' requires a 'str' object but received a 'int'

### ISSUE THREAD

**Issue by geofffoster** [saychelsea11/Finance_And_Covid_Tracking_Dashboard#2]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-678b8d5c69a2> in <module>
     28 
     29 vac_values = [atl_one_shot,two_shots,doses_del,shots_given,doses_used]
---> 30 vac_values = list(map(str.strip,vac_values))
     31 
     32 print ("At least 1 shot given: ",atl_one_shot)

TypeError: descriptor 'strip' requires a 'str' object but received a 'int'

**Comment by geofffoster** [comment]
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux

**Comment by saychelsea11** [comment]
@geofffoster Thanks for catching this! I noticed this as well yesterday. I was able to resolve the issue by changing the expected text used in the 'class' attribute for parsing as the corresponding text had changed on the NYT website. See the modified notebook for the fix. Let me know if it works for your now. I'll try to monitor any other anomalies such as this.

**Comment by geofffoster** [comment]
verified. Good bit of work btw.
