### ISSUE TITLE
Fed has moved the treasuries data

### ISSUE THREAD

**Issue by jcoffi** [saychelsea11/Finance_And_Covid_Tracking_Dashboard#3]
Just to let you know, the Treasury Department has moved the treasuries data.

https://home.treasury.gov/developer-notice-xml-changes

**Comment by saychelsea11** [comment]
@jcoffi Thanks for the note! This is where they seemed to have moved it: https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_yield_curve&field_tdr_date_value_month=202203

I have edited the code to add this new URL. Some minor code changes were also required to adjust to the changed XML format. 

Should be back up and running now.
